Model:
    name: "VST"
    depth: None
    pretrained: True

Test:
    Dataset:
        type: "RGB_Dataset"
        root: "data/RGB_Dataset/Test_Dataset"
        sets: ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S']
        transform_list:
            resize:
                size: [224, 224]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/SotA/VST"

Eval:
    gt_root: "data/RGB_Dataset/Test_Dataset"
    pred_root: "snapshots/SotA/VST"
    result_path: "results"
    datasets: ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S']
    metrics: ['Sm', 'mae', 'Em', 'maxF', 'avgF', 'wFm', 'IoUmaxF', 'maxIoU', 'meanIoU']